### ISSUE TITLE
Wht am I doing wrong?

### ISSUE THREAD

**Issue by cyclo-techtwister** [gigajew/WinXRunPE-x86_x64#1]
Doesn't seem to do anything? It runs with no errors, I put putty 64 bit but, never see calc in task manager. I tried using a 32bit file and then get error that it only supports 64bit? Also compiles fine with no errors.  What did I do incorrectly?

**Comment by gigajew** [comment]
make sure you compile your assembly as 64-bit if you are trying to inject into a 64-bit process, especially because Windows automatically chooses C:\Windows\SysWOW64 or C:\Windows\System32 automatically depending on your architecture.

So in three easy steps:
- Compile as 64-bit
- Use the 64-bit version of putty
- Pass the host as C:\Windows\System32\calc.exe

**Comment by onishn96** [comment]
im doing everything but still same problem .It runs with no errors but never see calc in taskmgr

**Comment by cyclo-techtwister** [comment]
Yea, no change here...
